version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=producto
      - DB_PASSWORD=${DB_PASSWORD:-producto_password}
      - DB_NAME=producto-db
      - DB_PORT=3306
      - API_URL=${API_URL:-http://localhost:3000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:19006}
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - producto-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=producto-db
      - MYSQL_USER=producto
      - MYSQL_PASSWORD=${DB_PASSWORD:-producto_password}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - producto-network
    ports:
      - "3306:3306"

networks:
  producto-network:
    driver: bridge

volumes:
  mysql-data: 