// frontend/src/screens/ScanScreen.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, BORDER_RADIUS, FONT_SIZE, FONT_WEIGHT, SHADOWS } from '../constants/colors';

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 0 : 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? SPACING.md : SPACING.xl,
    paddingBottom: SPACING.md,
    paddingHorizontal: SPACING.lg,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderBottomLeftRadius: SPACING.xl,
    borderBottomRightRadius: SPACING.xl,
    ...SHADOWS.md,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  headerTitle: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.primary,
    letterSpacing: 0.5,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.lg,
    width: '100%',
  },
  cameraContainer: {
    width: '90%',
    aspectRatio: 0.8,
    maxHeight: 420,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: SPACING.md,
    position: 'relative',
    backgroundColor: COLORS.card,
    borderRadius: SPACING.xl,
    ...SHADOWS.lg,
    padding: SPACING.xs,
    paddingBottom: 60,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  camera: {
    width: '100%',
    height: '100%',
    borderRadius: BORDER_RADIUS.lg,
    overflow: 'hidden',
  },
  scanFrame: {
    position: 'absolute',
    width: '70%',
    aspectRatio: 1,
    borderRadius: BORDER_RADIUS.lg,
    zIndex: 2,
    borderStyle: 'dashed',
    backgroundColor: 'transparent',
    top: '22.5%',
  },
  scanHint: {
    position: 'absolute',
    bottom: SPACING.xs,
    width: '100%',
    textAlign: 'center',
    color: COLORS.text,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.medium,
    zIndex: 3,
    letterSpacing: 0.5,
    paddingHorizontal: SPACING.lg,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingVertical: 6,
    borderRadius: BORDER_RADIUS.sm,
    marginHorizontal: SPACING.md,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: BORDER_RADIUS.lg,
    margin: SPACING.lg,
    padding: SPACING.xxl,
    ...SHADOWS.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  resultsContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
  },
  errorContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.xl,
    marginVertical: SPACING.md,
    alignItems: 'center',
    ...SHADOWS.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    width: '100%',
    maxWidth: 400,
  },
  errorText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.error,
    textAlign: 'center',
    marginBottom: SPACING.lg,
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: 22,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
    ...SHADOWS.sm,
  },
  createButtonText: {
    color: COLORS.card,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.bold,
  },
  adminNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  adminNoticeText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.muted,
    marginLeft: SPACING.xs,
    fontWeight: FONT_WEIGHT.medium,
  },
  scanAgainButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOWS.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    marginTop: SPACING.lg,
    width: '100%',
    maxWidth: 300,
  },
  scanAgainText: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.bold,
  },
  infoText: {
    fontSize: FONT_SIZE.lg,
    color: COLORS.text,
    textAlign: 'center',
    marginTop: SPACING.xxxl,
    fontWeight: FONT_WEIGHT.medium,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: SPACING.lg,
    borderRadius: BORDER_RADIUS.lg,
    ...SHADOWS.sm,
  },
});

export default styles; 